version: 1

name: identity-flag-types

pipelines:
  dev:
    phases:
    - type: github
      name: github
      owner: byu-oit
      repo: domain-identity-flag_types
      branch: master
    - type: codebuild
      name: build
      build_image: aws/codebuild/nodejs:6.3.1
    - type: handel
      name: deploy
      environments_to_deploy:
      - dev
